spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/obs_db
spring.datasource.username=postgres
spring.datasource.password=#Vedant13
spring.jpa.hibernate.ddl-auto=update